/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultArchetypeRouteImport } from './routes/result.$archetype'
import { Route as ApiPublicSubmitLeadRouteImport } from './routes/api/public/submit-lead'

const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultArchetypeRoute = ResultArchetypeRouteImport.update({
  id: '/result/$archetype',
  path: '/result/$archetype',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSubmitLeadRoute = ApiPublicSubmitLeadRouteImport.update({
  id: '/api/public/submit-lead',
  path: '/api/public/submit-lead',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quiz': typeof QuizRoute
  '/result/$archetype': typeof ResultArchetypeRoute
  '/api/public/submit-lead': typeof ApiPublicSubmitLeadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quiz': typeof QuizRoute
  '/result/$archetype': typeof ResultArchetypeRoute
  '/api/public/submit-lead': typeof ApiPublicSubmitLeadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quiz': typeof QuizRoute
  '/result/$archetype': typeof ResultArchetypeRoute
  '/api/public/submit-lead': typeof ApiPublicSubmitLeadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/quiz' | '/result/$archetype' | '/api/public/submit-lead'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/quiz' | '/result/$archetype' | '/api/public/submit-lead'
  id:
    | '__root__'
    | '/'
    | '/quiz'
    | '/result/$archetype'
    | '/api/public/submit-lead'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuizRoute: typeof QuizRoute
  ResultArchetypeRoute: typeof ResultArchetypeRoute
  ApiPublicSubmitLeadRoute: typeof ApiPublicSubmitLeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$archetype': {
      id: '/result/$archetype'
      path: '/result/$archetype'
      fullPath: '/result/$archetype'
      preLoaderRoute: typeof ResultArchetypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/submit-lead': {
      id: '/api/public/submit-lead'
      path: '/api/public/submit-lead'
      fullPath: '/api/public/submit-lead'
      preLoaderRoute: typeof ApiPublicSubmitLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuizRoute: QuizRoute,
  ResultArchetypeRoute: ResultArchetypeRoute,
  ApiPublicSubmitLeadRoute: ApiPublicSubmitLeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
